services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.development
    ports:
      - "3080:3080"
    networks:
      - labelprint-network
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development

networks:
  labelprint-network:
    driver: bridge
